import React from "react";
import { Link, useNavigate, useLocation, useParams, useSearchParams } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";
import "../anime-errors.css";

interface Error4xxProps {
  code?: number;
  title?: string;
  message?: string;
}

const ERROR_4XX_DETAILS: Record<number, { title: string; desc: string; badge: string; sector: string }> = {
  400: {
    title: "CORRUPTED QUANTUM PACKET",
    desc: "The neural node received an illegible or malformed request payload. The zero-trust gateway rejected the cipher frame.",
    badge: "ERR_400 // BAD_REQUEST",
    sector: "SECTOR://DECRYPT-FAIL",
  },
  401: {
    title: "UNAUTHORIZED CIPHER CLEARANCE",
    desc: "Your cryptographic credentials or session token are missing or have expired. Re-authentication is required to access the vault node.",
    badge: "ERR_401 // AUTH_REQUIRED",
    sector: "SECTOR://GATEWAY-GATE-01",
  },
  402: {
    title: "SECURITY TOKENS DEPLETED",
    desc: "Access to this decentralized enclave requires operational gas or subscription credentials. Top up cryptographic credits to proceed.",
    badge: "ERR_402 // PAYMENT_REQUIRED",
    sector: "SECTOR://CRYPTO-LEDGER",
  },
  403: {
    title: "SECURITY PROTOCOL VIOLATION",
    desc: "Access denied by Zero-Trust policy. Your identity lacks permission clearance for this encrypted terminal node.",
    badge: "ERR_403 // FORBIDDEN_ZONE",
    sector: "SECTOR://BLACK-ICE-RESTRICTED",
  },
  404: {
    title: "CYBERSPACE PATH NOT FOUND",
    desc: "The digital coordinate you entered vanished into the dark fiber void or never existed. Check your vector and try again, operative.",
    badge: "ERR_404 // NODE_NOT_FOUND",
    sector: "SECTOR://VOID-MATRIX-NULL",
  },
  405: {
    title: "METHOD REJECTED BY FIREWALL",
    desc: "The protocol verb or transmission method attempted is strictly forbidden on this cryptographic route.",
    badge: "ERR_405 // METHOD_NOT_ALLOWED",
    sector: "SECTOR://GATEWAY-RESTRICTED",
  },
  406: {
    title: "INCOMPATIBLE CIPHER FORMAT",
    desc: "The client terminal cannot accept the cryptographic output headers generated by the zero-trust cluster.",
    badge: "ERR_406 // NOT_ACCEPTABLE",
    sector: "SECTOR://NEGOTIATION-FAULT",
  },
  407: {
    title: "PROXY AUTHENTICATION FAILED",
    desc: "The intermediary mesh proxy requires identity verification before relaying packets to the core vault.",
    badge: "ERR_407 // PROXY_AUTH_REQUIRED",
    sector: "SECTOR://EDGE-PROXY-03",
  },
  408: {
    title: "TRANSMISSION EPOCH TIMEOUT",
    desc: "The handshake socket timed out while awaiting the client's cryptographic nonce. The connection was terminated.",
    badge: "ERR_408 // REQUEST_TIMEOUT",
    sector: "SECTOR://CHRONO-BUFFER-EXPIRED",
  },
  409: {
    title: "CRYPTOGRAPHIC CONFLICT DETECTED",
    desc: "A concurrent modification, duplicate account identifier, or cryptographic state collision occurred in the ledger.",
    badge: "ERR_409 // CONFLICT",
    sector: "SECTOR://STATE-COLLISION",
  },
  410: {
    title: "NODE PERMANENTLY PURGED",
    desc: "This data vector has been intentionally scrubbed from the encrypted shard network. No forward address exists.",
    badge: "ERR_410 // GONE",
    sector: "SECTOR://BLACK-HOLE-ARCHIVE",
  },
  411: {
    title: "CONTENT LENGTH UNDEFINED",
    desc: "The zero-trust firewall requires explicit packet byte boundaries to prevent buffer overflow injections.",
    badge: "ERR_411 // LENGTH_REQUIRED",
    sector: "SECTOR://FIREWALL-DEFENSE",
  },
  412: {
    title: "PRECONDITION EVALUATION FAILED",
    desc: "One or more cryptographic conditional headers (ETags, cipher revisions) evaluated to false.",
    badge: "ERR_412 // PRECONDITION_FAILED",
    sector: "SECTOR://STATE-GUARD",
  },
  413: {
    title: "CIPHER PAYLOAD OVERFLOW",
    desc: "The encrypted file or vault item exceeds the maximum allowed payload quota (100KB limit).",
    badge: "ERR_413 // PAYLOAD_TOO_LARGE",
    sector: "SECTOR://QUOTA-BREACH",
  },
  414: {
    title: "URI VECTOR BUFFER OVERFLOW",
    desc: "The requested URL address string is abnormally long and was truncated to protect neural router stability.",
    badge: "ERR_414 // URI_TOO_LONG",
    sector: "SECTOR://ROUTER-OVERFLOW",
  },
  415: {
    title: "UNSUPPORTED CIPHER SUITE",
    desc: "The media or payload format transmitted is not recognized by the zero-trust encryption subsystem.",
    badge: "ERR_415 // UNSUPPORTED_MEDIA",
    sector: "SECTOR://MIME-VERIFICATION",
  },
  416: {
    title: "BYTE RANGE UNSATISFIABLE",
    desc: "The requested stream offset lies outside the cryptographic boundaries of the encrypted container.",
    badge: "ERR_416 // RANGE_OUT_OF_BOUNDS",
    sector: "SECTOR://STORAGE-STRIPE",
  },
  417: {
    title: "EXPECTATION REJECTED",
    desc: "The node cannot fulfill the requirements outlined in the transmission Expect header frame.",
    badge: "ERR_417 // EXPECTATION_FAILED",
    sector: "SECTOR://ENCLAVE-INSPECT",
  },
  418: {
    title: "CYBERNETIC TEAPOT PROTOCOL",
    desc: "Node refuses to brew coffee; it is permanently configured as an encrypted cybernetic teapot.",
    badge: "ERR_418 // IM_A_TEAPOT",
    sector: "SECTOR://COFFEE-MATRIX",
  },
  421: {
    title: "MISDIRECTED QUANTUM PACKET",
    desc: "The request was routed to a server instance incapable of producing a response for this cryptographic authority.",
    badge: "ERR_421 // MISDIRECTED_REQUEST",
    sector: "SECTOR://DNS-WARP",
  },
  422: {
    title: "UNPROCESSABLE CIPHER ENTITY",
    desc: "The request data was syntactically valid JSON, but cryptographic fields failed schema or key-size validation.",
    badge: "ERR_422 // VALIDATION_FAILURE",
    sector: "SECTOR://SCHEMA-GUARD",
  },
  423: {
    title: "ACCOUNT DEFENSIVELY LOCKED",
    desc: "Too many consecutive authentication failures triggered an automated defense lockout to prevent credential stuffing.",
    badge: "ERR_423 // DEFENSIVE_LOCKOUT",
    sector: "SECTOR://LOCKOUT-VAULT",
  },
  424: {
    title: "FAILED CIPHER DEPENDENCY",
    desc: "This operation failed because an essential prerequisite transaction or key exchange was aborted.",
    badge: "ERR_424 // FAILED_DEPENDENCY",
    sector: "SECTOR://TX-CHAIN",
  },
  425: {
    title: "REPLAY ATTACK CONTAINMENT",
    desc: "The server refused the request to mitigate risk of 0-RTT early data replay vulnerabilities.",
    badge: "ERR_425 // TOO_EARLY",
    sector: "SECTOR://ANTI-REPLAY",
  },
  426: {
    title: "CRYPTOGRAPHIC UPGRADE REQUIRED",
    desc: "The terminal must negotiate a newer TLS protocol or updated cipher suite to access this node.",
    badge: "ERR_426 // UPGRADE_REQUIRED",
    sector: "SECTOR://CRYPTO-AGILITY",
  },
  428: {
    title: "PRECONDITION HEADER REQUIRED",
    desc: "The origin requires conditional headers to prevent race conditions during distributed vault synchronizations.",
    badge: "ERR_428 // PRECONDITION_REQUIRED",
    sector: "SECTOR://SYNC-RACE-GUARD",
  },
  429: {
    title: "NEURAL RATE LIMIT TRIGGERED",
    desc: "You have exceeded the transmission rate limit. The cyber perimeter has instituted cooling measures.",
    badge: "ERR_429 // RATE_LIMIT_EXCEEDED",
    sector: "SECTOR://BRUTE-FORCE-SHIELD",
  },
  431: {
    title: "HEADER BUFFER EXCEEDED",
    desc: "The cryptographic headers or auth cookies are abnormally large. Clear browser credentials and retry.",
    badge: "ERR_431 // HEADERS_TOO_LARGE",
    sector: "SECTOR://INGRESS-BUFFER",
  },
  451: {
    title: "UNAVAILABLE DUE TO CENSORSHIP",
    desc: "Access to this node coordinate is restricted by sovereign cyber directives or legal enforcement mandate.",
    badge: "ERR_451 // LEGAL_RESTRICTION",
    sector: "SECTOR://SOVEREIGN-FIREWALL",
  },
};

export const Error4xxPage: React.FC<Error4xxProps> = ({ code: propCode, title, message }) => {
  const navigate = useNavigate();
  const location = useLocation();
  const params = useParams<{ code?: string }>();
  const [searchParams] = useSearchParams();
  const { token } = useAuth();

  // Resolve code dynamically: prop -> URL param (:code) -> query string (?code=) -> fallback 404
  const parsedParamCode = params.code ? parseInt(params.code, 10) : undefined;
  const parsedQueryCode = searchParams.get("code") ? parseInt(searchParams.get("code")!, 10) : undefined;
  const activeCode = propCode || parsedParamCode || parsedQueryCode || 404;

  const details = ERROR_4XX_DETAILS[activeCode] || {
    title: `CLIENT ANOMALY (${activeCode})`,
    desc: `The zero-trust client subsystem encountered an unhandled status code (${activeCode}). Cryptographic integrity preserved.`,
    badge: `ERR_${activeCode} // CLIENT_FAULT`,
    sector: `SECTOR://4XX-ANOMALY-MATRIX`,
  };

  const displayTitle = title || searchParams.get("title") || details.title;
  const displayDesc = message || searchParams.get("message") || details.desc;

  return (
    <div className="anime-container">
      <div className="anime-card">
        {/* Anime Art Column */}
        <div className="anime-image-wrapper">
          <img
            src="/images/anime-404.jpg"
            alt="Cyberpunk 4xx Anime Illustration"
            className="anime-image"
          />
          <div className="anime-scanline" />
        </div>

        {/* Informational Column */}
        <div>
          <div className="anime-badge">
            <span className="anime-status-dot" />
            <span>{details.badge}</span>
          </div>

          <h1 className="anime-code">{activeCode}</h1>
          <h2 className="anime-title">{displayTitle}</h2>
          <p className="anime-description">{displayDesc}</p>

          {/* HUD Diagnostics */}
          <div className="anime-hud-box">
            <div className="anime-hud-item">
              <span>TARGET VECTOR:</span>
              <span className="anime-hud-highlight">{location.pathname}</span>
            </div>
            <div className="anime-hud-item">
              <span>SECTOR NODE:</span>
              <span>{details.sector}</span>
            </div>
            <div className="anime-hud-item">
              <span>CRYPTO STATUS:</span>
              <span className="anime-hud-highlight">ZERO-KNOWLEDGE SHIELD ACTIVE</span>
            </div>
          </div>

          {/* Actions */}
          <div className="anime-actions">
            {token ? (
              <Link to="/vault" className="anime-btn-primary">
                <span>🛡️ Return to Vault</span>
              </Link>
            ) : (
              <Link to="/login" className="anime-btn-primary">
                <span>🔑 Log In to Node</span>
              </Link>
            )}

            <button
              type="button"
              onClick={() => {
                if (window.history.length > 1) {
                  navigate(-1);
                } else {
                  navigate("/vault");
                }
              }}
              className="anime-btn-secondary"
            >
              <span>↩ Step Back</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
